### ISSUE TITLE
Job Search Status labels confusing

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#100]
E.g. "No".

Last year I used the following in the charts:

* Not looking
* Not actively looking
* Actively looking

**Comment by SachaG** [comment]
<img width="756" alt="Screenshot 2023-11-09 at 10 52 59" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/8f15ceab-f41c-49e1-a98c-cb3ed1f1c908">

That doesn't match with the wording we used for the question itself though?

**Comment by SachaG** [comment]
So maybe instead:

- Actively looking
- Would consider a switch
- Not looking

?

**Comment by pwim** [comment]
I agree your wording is better. Let's go with that.
