### ISSUE TITLE
Country or Region salary breakdown broken

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#103]
New Zealand and others with a small sample size are showing ¥0:
<img width="929" alt="Screenshot 2023-11-10 at 10 40 05" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/7fd3736e-b16d-4ca6-b008-c8f17cb8f7fd">

**Comment by SachaG** [comment]
This is fixed locally, I just need to redeploy.
