### ISSUE TITLE
Allow combining facets and filters at the same time

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#104]
And having a grid (small multiples) view of multiple facet breakdowns.

**Comment by pwim** [comment]
I'd like to bump this as it came up again. I wanted to see the salary percentiles by experience and employer type.

**Comment by pwim** [comment]
Is it possible to hard code that one? It looks like the data might be pretty interesting.

**Comment by SachaG** [comment]
This is already possible actually, it should work on https://2023.stateofhtml.com/

I just need to merge those latest changes back to the TokyoDev repo.

**Comment by SachaG** [comment]
This should work on https://tokyodev-results-2024.onrender.com/

Let me know what exactly you'd like to combine.

**Comment by pwim** [comment]
Perfect! Being able to do charts like this is what I was looking for.

<img width="1321" alt="Screenshot 2024-06-28 at 13 58 53" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/ff1b22db-8fe1-4531-b355-c4d62b41b5b1">
