### ISSUE TITLE
"Years in Japan" with "Professional Experience" facet throws error

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#105]
```
Right side of assignment cannot be destructured
```

**Comment by pwim** [comment]
This is only a bug if you do it via the "All Respondents" tab. It works via "Salary Breakdown".

**Comment by SachaG** [comment]
Oh right that's because the Years in Japan chart uses a vertical bar chart, so it tries to use the vertical boxplot which is still a work in progress. Maybe I should just switch everything to use horizontal bar charts?
