### ISSUE TITLE
Country or Region excludes "Other answers" / "No answers"

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#117]
This may have been intentional, but it is confusing to me why it was excluded.

Also, could you give me a count of the unique countries across all answers?

**Comment by SachaG** [comment]
Oh, this is because of how the results interact with the `limit` variable, which defaults to 20. Let me think about how to handle it. 

As for the count, there's 68 different countries.

**Comment by pwim** [comment]
In my previous survey, I collapsed everything over the `limit` into "Other Answers"

**Comment by SachaG** [comment]
Yeah that would make more sense. Or I can just use a cutoff instead of a limit.
