### ISSUE TITLE
Delete "Self-taught" from "Professional Qualifications"

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#118]
Being self taught isn't a professional qualification. Having it in the results is a bit misleading to me, so let's remove it.

**Comment by SachaG** [comment]
OK. Just fyi, to remove it I just had to remove the regex that matched "self taught" in the freeform answers and renormalize that question's data. Now that this token is not being matched anymore those answers will just fall into the "unmatched answers" bucket, which itself shows up as "other answers" in the results.
