### ISSUE TITLE
Professional Qualifications with Professional Experience Facet Broken

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#119]
<img width="1128" alt="Screenshot 2023-11-13 at 13 29 41" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/25414b38-27e9-42cc-9062-863e5128534d">

**Comment by SachaG** [comment]
I ran into a similar issue but now I can't seem to reproduce it. Weird.
