### ISSUE TITLE
Extra question specific tabs for demographics

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#121]
- Japanese prefecture: Remote Work Policy Facet
- Reason for Relocation: Employer Type Facet
- Residency Status: Employer Type Facet
- Country or Region: Japanese Prefecture
- Age: Side-by-side; Gender is Man; Gender is Woman; No default
- Professional Experience: Side-by-side; Gender is Man; Gender is Woman; No default
- Professional Qualifications: Professional Experience Facet, Gender Facet [If two extra are going to break the layout, let's go with experience)
- Japanese Ability: Years in Japan

**Comment by SachaG** [comment]
<img width="976" alt="Screenshot 2023-11-14 at 7 17 40" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/d9fda942-1f37-4614-aafd-c5a709d03c70">

Country or Region: Japanese Prefecture is not very revealing…
