### ISSUE TITLE
Don't show all countries when using country facet

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#123]
Same with Japanese Prefecture facet.

**Comment by pwim** [comment]
I'd generalize this. If a given answer doesn't show up in the chart, don't show it. (I noticed the same thing happening for Gender as well)

**Comment by SachaG** [comment]
That was actually really hard to do, because the component that shows the legends didn't have access to the dynamic data requested from the API. I think I made it work, hopefully that doesn't break too many other things…
