### ISSUE TITLE
Question specific tabs for Job

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#124]
- Role: Educational Attainments facet
- Other Engineers' Nationalities: Years in Japan
- Japanese Usage: Employer Type
- English Usage: Employer Type
- Job finding method: Employer Type

**Comment by SachaG** [comment]
<img width="941" alt="Screenshot 2023-11-16 at 9 21 10" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/b3b6d888-5a75-4a87-9a23-304ed4ff33ed">

Job finding method: Employer Type doesn't give that much insights since it's pretty much the same thing.
