### ISSUE TITLE
Compensation specific tabs

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#132]
* Previous Compensation: Negotiated Compensation facet
* Desired Compensation: Negotiated Compensation facet
* Negotiated Compensation: Side-by-side; Employer Type is A company headquartered in Japan; Employer Type is A Japanese subsidiary of an international company; no default

**Comment by SachaG** [comment]
Previous/Desired Compensation vs Negotiated Compensation feels a bit confusing to me?
