### ISSUE TITLE
Turn off percentiles for Employer Size

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#134]
% of bucket is more useful

**Comment by SachaG** [comment]
Do you mean for when Employer Size is used as a facet? I don't think there's really an easy way to turn it off there specifically, at least not currently…

**Comment by pwim** [comment]
Yes, when it used as facet. 

The percentiles currently only exist for a subset of numbers. Like they don't show up for age or hours per day. What's the difference between employer size and those?

**Comment by SachaG** [comment]
Questions have a `optionsAreRange` property to indicate if their content is in the form of numerical ranges. Percentiles are enabled for those where it's set to `true`, which is the case for `company_size` (the employer size question). We could add an `enablePercentiles` property or something but I'm worried about having too many single-use properties that become hard to keep track of…

**Comment by SachaG** [comment]
Oh btw I forgot to mention that we can't turn it off, but we can make the chart default to one tab or another. I'll just do that for now.
