### ISSUE TITLE
Better error management when API returns an error

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#138]
When customizing a chart

**Comment by pwim** [comment]
We're already using Sentry, which supports JS monitoring, so if you used that, I think we could plug it into our existing account.

**Comment by SachaG** [comment]
<img width="894" alt="Screenshot 2023-11-14 at 19 08 25" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/aa43580c-df32-4a38-9ae6-7ae5fe57af0a">

Good point about Sentry, but I also like having a link to submit a GitHub issue because it makes it easier to follow up with the user.
