### ISSUE TITLE
Add Other Questions Tabs

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#139]
- Add Salary breakdown for all the questions
- Visa situation: 
  - Residency Status is Engineer/Specialist in Humanities/International Services
  - Residency Status is Permanent resident
- Developer Communities: Gender Facet
- Family Life:
  - Age is 20-29
  - Age is 30-39
- Social Life
  - Japanese Ability is one of None, Basic
  - Japanese Ability is one of Native / bilingual, Fluent

**Comment by SachaG** [comment]
@pwim Now that the satisfaction questions work as facets let me know if you still want to have the chart variants outlined here, or if you want to "reverse" them to facet other charts by satisfaction instead.

**Comment by pwim** [comment]
While having them as facets is great, I think it might be easier to highlight differences with the charts I proposed.

For instance, with residency status and the visa satisfaction facet, 3 vs 4 looks quite similar:

<img width="1387" alt="Screenshot 2023-11-17 at 7 34 48" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/ca4beb77-9e0c-4458-b65d-a9b14cdd6b7e">

The % of bucket perhaps highlights the difference better, though it isn't immediately obvious

<img width="1334" alt="Screenshot 2023-11-17 at 7 38 08" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/5424feba-7a05-4cac-a8b2-33271215ed29">

Whereas the side-by-side allows us to highlight specific differences

<img width="1377" alt="Screenshot 2023-11-17 at 7 33 47" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/11312dec-0e20-4eae-9597-f916698da68b">

Let's continue with having the takeaways / charts be on the individual satisfaction questions. Maybe in next years survey we can figure out a better way of highlighting them via facets.
