### ISSUE TITLE
Try a different font

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#153]
Now that this survey has lengthy takeaways, it might make sense to use a non-monospace font.

**Comment by SachaG** [comment]
<img width="1464" alt="Screenshot 2023-11-17 at 9 35 28" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/520bc94b-37c1-4cb6-993d-97132698c427">

**Comment by SachaG** [comment]
Are you ok with the new font or should I switch back? I used the same font stack as TokyoDev.com, so at least it's visually consistent.

**Comment by pwim** [comment]
Sure, let’s go with the new font.
