### ISSUE TITLE
Conclusion text

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#159]
``` markdown
With this year's survey, we've taken a big step forward by allowing readers like yourself the ability to create their own custom charts. While we've highlighted some correlations we think are interesting, there's more to be discovered, so please explore the data.

Providing this functionality while preserving the anonymity of participants was paramount to us. It was only possible that we were able to do it thanks to the 700+ people who took the survey, so a big thank you to everyone who took it!

TokyoDev runs this survey to help engineers from around the world understand what it is like working in Japan. If you're considering your move here, check out [our guide on how to get a software developer job in Japan](<https://www.tokyodev.com/articles/first-job-programmer-japan>), or jump in to [our list of English-friendly developer jobs](https://www.tokyodev.com/jobs).

If you're interested in hearing from us the next time we launch a survey, please sign up for our mailing list.

You can also join the [3000+ developers on our Discord](https://discord.gg/seUNe38YgV) to discuss developer life in Japan.
```

Repeat the contributors / about TokyoDev section from https://surveys.tokyodev.com/en-US/survey/tokyodev/2023

**Comment by SachaG** [comment]
My only two pieces of feedback would be that it feels a little late to tell people they can customize the chart (would be better suited for the intro); and also I feel like it's lacking some kind of parting words at the end?

**Comment by SachaG** [comment]
I'll edit it a bit and you can tell me what you think .

**Comment by SachaG** [comment]
> If you're considering your move here

Generally speaking in terms of overall marketing strategy, I think you probably want to avoid any language that seems to restrict the appeal of TokyoDev to people who are already planning on moving to Japan? I think there's a much larger segment of the developer population that is more at the "vaguely interested in maybe one day working in Japan" stage, and it seems like a shame to filter them out through language that's too restrictive?

**Comment by pwim** [comment]
Good points. I added a tweaked version in #167. It could probably use some more love, but I think it is good enough for now.
