### ISSUE TITLE
Additional tabs

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#168]
- Professional Life by Remote Work
  - Remote Work Policy is Hybrid. 
  - Remote Work Policy is one of Up to the employee. Employees can choose whether to work remotely or in the office., Fully remote. All employees work completely remotely
- Housing Satisfaction  By Prefecture
  - Japanese Prefecture is one of Tokyo, Chiba, Saitama, Kanagawa
  - Japanese Prefecture is not one of Tokyo, Chiba, Saitama, Kanagawa

**Comment by SachaG** [comment]
I think we could use "Remote Work Policy is one of No Remote Work, Hybrid." instead?
