### ISSUE TITLE
Decide about mailing list text

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#171]
> Don't Miss the Next Survey
> Leave us your email and we’ll let you know when the next survey takes place.

This is a bit misleading, as we'll also send them other TokyoDev emails.

**Comment by SachaG** [comment]
How about:

> Join the TokyoDev mailing list to receive a selection of our best Japan-based software engineer job offers, and know when the next survey takes place.

**Comment by pwim** [comment]
> Join the TokyoDev mailing list to receive a curated selection of Japan-based software engineer jobs for English speakers, and know when the next survey takes place.
