### ISSUE TITLE
Clarify what insufficient data means

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#176]
A reader was confused as to what it means. Something like a tool tip popup with an explanation of our strategy might help.

**Comment by SachaG** [comment]
<img width="649" alt="Screenshot 2023-11-27 at 14 52 47" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/0ce7698b-f1e3-4e17-a1bd-f647669250fa">
