### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#181]
- [ ] Remove unused keys
- [ ] Integrate with 3rd-party system?

**Comment by SachaG** [comment]
I think for starters I'm going to do what you suggested and use our "regular" non-Tokyodev strings as fallbacks, so that only the strings specific to TokyoDev remain in the repo.

**Comment by SachaG** [comment]
OK so going forward we will first load en-US and ja-JP locales from https://github.com/Devographics/locale-en-US and https://github.com/Devographics/locale-ja-JP; then load the same locales from this current repo; and merge everything down so that the TokyoDev strings take priority over the Devographics strings.

**Comment by SachaG** [comment]
OK, I've added the files that need to be translated: 

https://github.com/tokyodev-inc/tokyodev-devographics/tree/main/locales/locale-ja-JP

### Needed to run the next survey:

- `tdquestions.yml`: contains the strings for all questions. I didn't split them by survey because there's a lot of overlap. 
- `td2024.yml`: contains strings used by the 2024 survey specifically (such as the FAQ)

### Needed to publish the next results:

- `tdresults.yml`: contains strings used by the published results for all surveys
- `td2024.yml`: will also contains strings used by the 2024 results specifically

### Optional: 

- `td2023.yml`: if we want to translate last year's results as well

**Comment by pwim** [comment]
I've passed `td2024.yml` and `tdquestions.yml` off for review. We need to make sure if anything gets changed in the interim in those keys, it gets flagged for review.

**Comment by SachaG** [comment]
Yes, I'll make sure I make separate commits for any locale files to make that easier to track.

**Comment by SachaG** [comment]
For consistency reasons with how other surveys work I'm going to rename `tdquestions.yml` to `tokyodev.yml`, but I'm not changing the contents.

**Comment by SachaG** [comment]
Oh one thing to note is that there will probably be keys that need to be translated back in the main `locale-ja-JP` repo used by all surveys (https://github.com/Devographics/locale-ja-JP), and not the TokyoDev-specific files.
