### ISSUE TITLE
[New Question] Which productivity tools do you use?

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#185]
- Notion
- Slack
- Discord
- Google Docs
- Jira
- Trello
- etc.

**Comment by pwim** [comment]
I'll ask about that. I feel like we should keep the list to ones that are used in software development though. Like docusign is probably out of the scope.

**Comment by pwim** [comment]
* Cybozu Office
* Chatwork

**Comment by SachaG** [comment]
> * Cybozu Office
> * Chatwork
> * Cosense

Did you want me to add those? Or only keep the most popular options overall?
