### ISSUE TITLE
[New Question]  How many employers have you had while working in software development?

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#186]
Could be in your entire career/over the last X years.

The goal would be to see if workers in Japan change job more/less frequently than elsewhere.

**Comment by pwim** [comment]
I'd ask about the total number to give parity with the question

> How many years of professional experience do you have in software development?

We could then calculate the average per respondent.

**Comment by SachaG** [comment]
So just to double check, this is for their entire career, not just in Japan?

**Comment by pwim** [comment]
Yes, I think it is best to do over the entire career, so we could compare it with years of professional experience.
