### ISSUE TITLE
[New Questions] Paid Leave & Holidays

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#189]
- What is your company's paid leave policy?
    - Fixed
    - unlimited
    - None (is that legal?)
    - ~Not applicable (freelancers)~ If we address freelancers, I'd rather do it in a more universal way.
- How many days of paid leave did you take last year?
    - Use ranges since people might not know the exact number
- In addition to paid leave, what types of leave does your company offer?
    - Sick days
    - Public holidays
    - New year’s holidays
    - Obon/Summer holidays

The goal would be figuring out if unlimited paid leave leads to more actual paid leave days taken or not.

**Comment by pwim** [comment]
> Which paid leave policy does your current employer adopt?

I wonder if this would be more useful to ask like

> What percentage of your paid leave do you use in a typical year?

- N/A. I don't have paid leave.
- N/A. I have unlimited paid leave.
- 0 to 19%
- 20 to 39%
- ...

There's an extra data point we get that way.

**Comment by SachaG** [comment]
But then aren't we asking the same thing twice, once in percentage, and once in absolute numbers? It seems a bit redundant?

But if we do, I think it might make more sense to switch the order:

- How many days did you take?
- What percentage of your total days did that represent?

**Comment by pwim** [comment]
There is some overlap between them. But they're also different, as one represents the days you're allowed to take whereas another is the days you actually took.

Reflecting on it some more though, asking about the percentage taken is probably the more interesting and useful data point, and also one we haven't asked before. Whereas the other vacation stuff we have from previous years.

So I'm now thinking we only ask something like "What percentage of your paid leave do you anticipate you'll use this year?" and eliminate the paid leave policy / paid leave days / additional holiday questions.

**Comment by SachaG** [comment]
The only thing is that it would've been to know how much vacation people with unlimited paid leave are actually taking. 

See: https://www.hr-brew.com/stories/2023/06/08/unlimited-versus-traditional-pto

**Comment by pwim** [comment]
Yeah, we're loosing out on that. But as unlimited paid leave is relatively uncommon among our audience, I'm not sure we could draw so deep conclusions (or that it'd be different than that article anyways).

**Comment by SachaG** [comment]
Maybe ask "What percentage of your paid leave do you typically use in a year?" to eliminate any outliers for the current year?

**Comment by pwim** [comment]
I suggested asking it about the current year because then we can draw correlations relating it to the current employer.

I don't think we need to worry about outliers, as by aggregating the results, we should already be eliminating that issue.

**Comment by SachaG** [comment]
OK, sounds good.
