### ISSUE TITLE
[New Question] What do you like most about your current job?

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#193]
Coworkers
Freedom
Flexibility
Culture
Work / Life Balance
Work Itself
Working Remotely
Personal Growth
Salary
Low Stress
Mission
Product
Job safety
Influence 
Responsibility
Technology Used
Company Itself
Other

---

Maybe let people pick top 3?

**Comment by pwim** [comment]
This question is meant to serve as a counterpoint to #182. The focus of that question is specific negative things they've encountered, as opposed to generally bad things. So I wonder how we could word this question similarly.

**Comment by SachaG** [comment]
Should we ask about the **current job** or the **workplace**? Same question with difficulties in the workplace. Whichever one we pick we should probably be consistent between both questions?

**Comment by pwim** [comment]
Good point. Let's focus on the workplace. So "What do you like most about your current workplace?"

**Comment by SachaG** [comment]
How about:

- Which difficulties have you encountered while working in Japan?
- What do you like most about working in Japan?

**Comment by SachaG** [comment]
Actually I'm still not 100% happy because "the Japanese workplace" is a bit ambiguous if you're working for a foreign company… Maybe try to match the two even more closely?

- Which workplace difficulties have you encountered while working in Japan?
- Which workplace perks have you enjoyed while working in Japan?

**Comment by pwim** [comment]
I think it is more useful if we tie it to the current job or company, as opposed to Japan generally. Then we can say if there are trends working for an international employer or Japanese one for instance.

I could see asking

* What are the negative aspects of the working environment at your current employer?
* What are the positive aspects of the working environment at your current employer?

That does make things a bit broader. But maybe it is good to be able to include things like "Sexism" as a negative aspect, as even people who aren't directly affected by it can report it (if it's something they observe).

**Comment by SachaG** [comment]
For me the downside is that if someone encounters sexism in their first 9 japanese jobs, but then the current one is sexism-free, we wouldn't capture that if we only ask about the current job? That's why I wanted to ask about people's overall experience.

**Comment by pwim** [comment]
Yeah. It's a tradeoff. But I think we casting a too wide net if it is something people have ever experienced in Japan.

Also, things change. Like I've been working in Japan for 20 years and there was definitely sexism and homophobia I saw when I first got here, but that isn't something I've experienced in my current one (and I hope everyone feels the same 😓).

**Comment by SachaG** [comment]
Hmm another reason I just thought of for not asking about the current workplace: people might be less inclined to be forthcoming with information about e.g. sexism if they think there's a chance it might somehow linked back to them. If we ask about "the workplace" there's more plausible deniability.

**Comment by SachaG** [comment]
It might be a bit outside the scope for now, but I could see some kind of "mirror" form UI where for each topic, you ask if it's an advantage of a difficulty.

**Comment by SachaG** [comment]
I managed to make the two list mirror each other's items:

<img width="700" alt="Screenshot 2024-07-01 at 15 59 10" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/e0bf8bf9-176f-41ef-8ca1-bb802d3b3a40">

<img width="696" alt="Screenshot 2024-07-01 at 15 59 19" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/5d2f187b-c26c-4ba6-8466-ec07ce6391a4">
