### ISSUE TITLE
[New Question] Colleague Gender (Engineers)

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#194]
What is gender of your colleagues who are engineers?

* All male
* Mostly male
* A mix
* Mostly female
* All female

**Comment by SachaG** [comment]
Do we want a more granular scale? Maybe just replace "mostly male" by "over 80% male"?

**Comment by pwim** [comment]
I was going for parity with our question about Colleague Nationality. I think this is something that's going to be based off perception, so something subjective is fine.
