### ISSUE TITLE
Revise colleague nationality questions

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#195]
Change options to

* All Japanese
* Mostly Japanese
* A mix of Japanese and non-Japanese
* Mostly non-Japanese
* All non-Japanese

**Comment by SachaG** [comment]
Should we differentiate between Japanese and non-Japanese companies?

e.g. if someone is working remotely for their company back in the U.S. then you wouldn't expect any of their colleagues to be Japanese.

There's also the case where someone is a freelancer or self-employed and doesn't have any colleagues, but I guess they can just skip the question.

**Comment by pwim** [comment]
I don't think we need to explicitly differentiate when asking this question. It's potentially a difference we could highlight in the results.
