### ISSUE TITLE
[New Question] How difficult was it to get your first job in software development job in Japan?

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#196]
- Very easy
- Easy
- Moderate
- Difficult
- Very difficult
- N/A (I haven't sought employment in software development in Japan)

---
Let's keep "Reason for relocation" to compare with this.

**Comment by pwim** [comment]
I think this captures what people care about more than #187

**Comment by SachaG** [comment]
I guess my only reservation would be that it's pretty subjective… but I'm not sure how we can ask this in a more objective way.

**Comment by pwim** [comment]
We could ask something like:

To get your first software developer job in Japan, how many positions did you apply to?

* 1 - 5
* 6 - 10
* 11 - 20
* 21 - 50
* 51 - 100
* 100 - 999
* 1,000 or more

I'm not sure if we'd explicitly want to address the case when someone was transferred to Japan by their existing employer.

**Comment by SachaG** [comment]
It might be hard for people to remember the number if it was a long time ago? But even so that's probably better than a subjective scale. Would people really apply to more than 1000 jobs though??

**Comment by pwim** [comment]
Unbelievable I know, but some people on the TokyoDev discord have mentioned applying to thousands of jobs...

I remember that I applied for two jobs when I first came to Japan, and got one of them. Maybe I'm an outlier, but I think people should have a general idea if not the exact number. We will be able to see when we run it by more people though, so let's go with that way for now.

**Comment by SachaG** [comment]
My only worry is that if i.e. 90% of people apply to between 1 and 4 jobs, then the data won't be very meaningful… Maybe we should do a quick informal poll on the Discord just to help us narrow down the scale.

**Comment by pwim** [comment]
Good idea. [Here it is](https://discord.com/channels/1011593503438012476/1019817446762360972/1256117380963373088).

**Comment by SachaG** [comment]
Someone raised the case of applying to e.g. 5 positions but being accepted to all of them. Would that count as 1 or 5?

**Comment by SachaG** [comment]
Oh we could ask about rejections instead. 

> How many rejections did you go through when applying for your first software developer job in Japan?

**Comment by pwim** [comment]
I wouldn't ask about rejections because it is negative, and also that many companies in Japan won't specifically reject you. 

When asking the number of jobs people apply to, it's just that. Not connected to how many offers they received. I think it is okay that some people get accepted more than others. The number of applications you send is still a rough proxy for the difficulty. Like if someone sends 5 and gets 1 offer, it's significantly different than if someone sends 50 applications and gets 1 offer.

I think we could ask something like:

> To get your first software developer job in Japan, how many positions did you apply to?
> *Only applications where you initiated the process count.*
> 
> * 0 (Internal transfer, was approached by a recruiter, etc)
> * 1 - 5
> * 6 - 10
> * 11 - 20
> * 21 - 50
> * 51+
