### ISSUE TITLE
[New Question] What is the best thing about your life in Japan?

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#197]
Free text question as the final one.

**Comment by pwim** [comment]
The question is currently

> What is the best thing about Japan?

Were you intending for it to be this generic? It sounds like what is best with the country, whereas I'm more interested in what's best for people personally.

**Comment by SachaG** [comment]
Ah good point, I didn't notice the nuance. Also, should we ask respondents to answer in one word? This might make parsing the results easier, otherwise I'm not sure we'll get any usable data…

**Comment by pwim** [comment]
We could try it. Something like

> In a word, what is your favourite thing about Japan?

I think "your favourite" is probably better than "the best", as it makes it more personal.

**Comment by SachaG** [comment]
OK, let's go with that.
