### ISSUE TITLE
Merge "Current Job" and "Employer" sections?

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#199]
I still get confused between the two, and "Employer" only has four questions. We could probably merge them?

**Comment by pwim** [comment]
Yeah, we could try that. I had them separate because I didn't want one section to be too long, but maybe that isn't so important (especially with the side nav).

**Comment by pwim** [comment]
But then, you could also argue that compensation goes in there too...

**Comment by SachaG** [comment]
Hmm… would it be clearer to split along "workplace" vs "job"?

"Workplace" would be the questions about perks/difficulties, colleagues, etc. and "job" would be everything else?

**Comment by pwim** [comment]
Yeah that could make sense. 

We could also rephrase questions the language questions to
> How frequently do you use Japanese at your workplace?

**Comment by SachaG** [comment]
Anyway I think that's more of a concern for displaying the results, not so much for asking the questions since that's a more linear process anyway.

**Comment by pwim** [comment]
What about rearranging Current Job, Employer, and Compensation into the following?

- Current Job
  - Employer type
  - Employer industry
  - Employer size
  - Employment status
  - Role 
  - Total compensation
- Working Environment
  - Colleague Nationality
  - Japanese / English Usage
  - Colleague gender
  - Hours / week
  - Remote work policy
  - Paid leave percentage
  - Perks / Difficulties
  - Most important benefit

Also, the following probably belong under "Other Questions":

- Job Search Status
- Number of applications
- Source

That'd keep demographics about the person themselves.

**Comment by pwim** [comment]
"Satisfaction" could be split out to its own thing too. That'd give me the ability to write some overview about it as a whole.

**Comment by SachaG** [comment]
Sounds good, I'll work on that tomorrow.
