### ISSUE TITLE
2024 Survey Illustration

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#200]
We used the Tokyo Tower as a backdrop to quickly identify the 2023 survey. For 2024, should we pick another Japan landmark? Some ideas:

- Mount Fuji
- Itsukushima Torii
- Kinkaku-ji 
- Himeji Castle
- Kiyomizu-dera Temple

**Comment by SachaG** [comment]
Or we can also go in a completely different direction altogether. But I do think it's useful to be able to quickly distinguish each survey visually via illustrations, colors, typography, etc. if only for ourselves when we're working across multiple editions (to compare data, etc.).

**Comment by pwim** [comment]
I don't have strong thoughts on the illustration. Maybe it is more important to do something like a different colour scheme to distinguish it from other surveys?

**Comment by SachaG** [comment]
I did this for now, we can always change it later. 

![image](https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/d67bf299-cf86-4bcf-b83c-ecd538ccad85)
