### ISSUE TITLE
Trim list of technologies

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#201]
Let's only list ones that we got a significant number of results for last year (e.g. removing the Japanese cloud platforms). 

Also, I'd like to have at most 10 or so options for productivity tools.

**Comment by SachaG** [comment]
Yeah, I kind of listed all the major ones I could think of. I'm not sure according to which criteria to trim down the list though, I guess I can take my best guess according to popularity?

**Comment by SachaG** [comment]
I cleaned up all the lists a bit. Some items I decided to leave it even despite poor results if it's something whose absence would seem conspicuous (e.g. Angular); or something where we might anticipate year-over-year growth (e.g. Rust).
