### ISSUE TITLE
Note for Total Employers

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#205]
Something like

> Over your entire career, both in Japan and abroad.

**Comment by SachaG** [comment]
<img width="736" alt="Screenshot 2024-07-18 at 15 02 05" src="https://github.com/user-attachments/assets/77a86b37-800e-4ae8-9a49-d04c7bca6a0c">

**Comment by SachaG** [comment]
Oh, what about freelancers?

**Comment by pwim** [comment]
As freelancers are an edge case, I don't want to worry about mentioning how they should handle each different question where they'll potentially have an answer that won't fit well.
