### ISSUE TITLE
Number of applications

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#206]
Add a note like

> Only count positions where you initiated the application process.

and reword the option

> 0 (internal transfer, recruiter, etc. )

to something like

> 0 (internal transfer, scouted by recruiter, etc.)

**Comment by SachaG** [comment]
<img width="733" alt="Screenshot 2024-07-18 at 15 04 09" src="https://github.com/user-attachments/assets/75907d5e-c156-49db-8fd7-70718f73821d">
