### ISSUE TITLE
Paid Leave Percentage

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#209]
> Could not load question paid_leave_percentage (Question paid_leave_percentage does not have any options defined.)

**Comment by SachaG** [comment]
Oh right, did we want to use a number input for this? Or ranges?

**Comment by pwim** [comment]
Ranges, as I don't think anyone is going to calculate the exact percentage. I might go with:

- 0%
- 1-9%
- 10 - 19%
- ...
- 90 - 99%
- 100%

**Comment by SachaG** [comment]
If it's ranges we maybe shouldn't split out 0 and 100, this way it doesn't bias the data against those two datapoints?

**Comment by SachaG** [comment]
Also maybe 20% increments is granular enough?

**Comment by pwim** [comment]
My thinking was that those are data points that have special significance. There's also 101 numbers between 0 and 100, so it's not like we can get the ranges totally even anyways.

But thinking about it some more, if you take 0 days of vacation or 2 days of vacation, perhaps it's not so different. So I guess we could go with the larger increments.

**Comment by SachaG** [comment]
How about this then?

<img width="675" alt="Screenshot 2024-07-19 at 15 10 27" src="https://github.com/user-attachments/assets/54162a7e-141d-4513-a3b8-5182f049d08b">

**Comment by pwim** [comment]
Sure. We probably need a hint like

> This only refers to your usage of annual paid leave, and not to other holidays like national holidays, New Year's holidays, Obon, etc.
