### ISSUE TITLE
New question: Most important benefit

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#221]
> Besides your salary, which benefit your employer offers is most important to you (if any)?

* Books (free or subsidized)
* Company clubs or activities
* Food and drinks (free or subsidized)
* Generous vacation policy
* Japanese lessons (free or subsidized)
* Housing allowance or support
* No overtime
* Remote work
* RSUs or stock options
* Training (free or subsidized)
* Other

**Comment by SachaG** [comment]
Should we reuse the same list as the "advantages of japanese workplaces" question for consistency? Or are the questions different enough?

By the way, we also have the option to ask people to pick their top 3 (or top anything) if we want to give them a bit more freedom.

**Comment by pwim** [comment]
You're right there is some overlap.

However, their intention is different.

The positive aspects questions is trying to capture any positive aspects of the workplace, and divides things into broad categories.

This question is focused on things that employers explicitly offer as "benefits". Part of the motivation is that this is to help companies themselves to decide what to offer. This isn't necessarily the case with the positive aspects. Like offering "Free books" is a lot easier than "Good coworker relations".

I thought about having multiple options, but I think that works best when most people have many benefits they like. In this case, the company might only offer one or two of them to begin with.
