### ISSUE TITLE
Remove "not applicable" options

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#236]
Since we have the "skip" feature I think we can remove the "n/a" option from most questions for consistency's sake.

**Comment by pwim** [comment]
There's a difference between "skip" and "n/a". Skip doesn't differentiate between people who didn't want to answer the question, vs those it doesn't apply to. So "n/a" gives us an extra data point. That extra data may not be worth the complexity, but it's something to consider.

**Comment by SachaG** [comment]
Well, what prompted me to think about this is we have questions such as: 

> Which web frameworks do you regularly use at your job?

Which might not apply if you don't work on the web. But then we also have:

> What are the nationalities of your colleagues who are engineers?

Which might not apply if you work on your own as a freelancer. 

Currently, the first one has a "not applicable" option but not the second one, which didn't seem very consistent. 

I guess we could add "not applicable" to more questions, but then I feel like we'd just end up having to add it almost everywhere. So adding a note saying something along the line of "if something doesn't apply to you, skip the questioN" seemed more elegant.

**Comment by pwim** [comment]
You're right that it is kind of arbitrary when we have it but don't, so please go ahead and remove it altogether.
