### ISSUE TITLE
Chart descriptions/blurbs

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#24]
<img width="747" alt="Screenshot 2023-10-17 at 14 29 58" src="https://github.com/SachaG/tokyodev/assets/358832/3df6359c-14c4-4d23-83de-124191a91b1c">

Should I write the chart descriptions/blurbs? ("59% of respondents had a residency status tied…" etc.)

**Comment by pwim** [comment]
I'm working on this; I don't think it needs to be an issue.
