### ISSUE TITLE
Issues with Japanese version

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#243]
Please review the Japanese version and let me know of any additional strings that need to be translated.

**Comment by SachaG** [comment]
I found a couple missing strings: 

- user_info.user_info_intro_td2024
- options.languages_used_colleagues_japanese.always
- options.languages_used_colleagues_english.always

I went ahead and translated them myself, you can review that here: 

https://github.com/tokyodev-inc/tokyodev-devographics/commit/4e47b7b361977eeef96699c8cef87c92f529056b

The Industry Sector question also has some untranslated options but maybe that's on purpose?

**Comment by SachaG** [comment]
Industry Sector question:

<img width="743" alt="Screenshot 2024-08-20 at 14 38 21" src="https://github.com/user-attachments/assets/1a6705be-7038-47e7-b9a1-f95b159bceb6">

**Comment by pwim** [comment]
The industry options that are translated are coming from the base repo. Please provide the keys for the additional ones.

There continues to be other issues:

* Gender options aren't showing translations
* > 国民の祝日や年末年始、お盆休暇を除き、ご自身が取得する有給休暇について回答してください。 like national holidays, New Year's holidays, Obon, etc.
* Angular's "One framework. Mobile & desktop.", npm's "A package manager for JavaScript" etc aren't translated. Personally I think these aren't adding value, so we could just remove them if that's possible.
* Development process names and descriptions

**Comment by SachaG** [comment]
Fixed. The only thing that's a bit trickier are the development process names, because they're technically treated as entities (same as libraries, companies, people, etc.), whose names are not localized. I think it's probably ok to leave them in english though?

If not I will change them to just being treated as regular strings.

**Comment by SachaG** [comment]
Oh and here are the missing Industry Sector strings:

```

  - key: options.industry_sector.recruiting
    t: Recruiting
  - key: options.industry_sector.agency
    t: Agency
  - key: options.industry_sector.business
    t: Business
  - key: options.industry_sector.communication
    t: Comunication
  - key: options.industry_sector.security
    t: Security

  - key: options.industry_sector.ai
    t: Artificial Intelligence (AI)
  - key: options.industry_sector.advertising
    t: Advertising
  - key: options.industry_sector.cloud_computing
    t: Cloud Computing
  - key: options.industry_sector.consumer_electronics
    t: Consumer Electronics
  - key: options.industry_sector.food
    t: Food
  - key: options.industry_sector.hospitality_tourism
    t: Hospitality / Tourism
  - key: options.industry_sector.fashion
    t: Fashion
  - key: options.industry_sector.robotics
    t: Robotics
  - key: options.industry_sector.saas
    t: SaaS (Software as a Service)
```

**Comment by pwim** [comment]
I think we can just treat the development processes as strings. If I have to choose, I'd rather localize them to Japanese than have an extended description.

**Comment by pwim** [comment]
The options you've provided for Industry Sector don't match what we're asking. I.e. "Human Resources" is missing but "Business" is included.

**Comment by SachaG** [comment]
Sorry, that was just the list of what isn't translated, not necessarily what we're using. But since people have the option to answer "other" I think it's good to have more options translated anyway.

**Comment by SachaG** [comment]
<img width="775" alt="Screenshot 2024-08-22 at 9 00 27" src="https://github.com/user-attachments/assets/343b2a32-54a1-427d-aaa8-57045e5a485f">

Done. 

I didn't translate the industry sectors myself because I feel like there's more chances for me to get them wrong.

**Comment by pwim** [comment]
Whereas the industries weren't showing up as translated before, now most of them are. Maybe something changed when you deployed something?

Also, I noticed there's some changes from last year:

* Blockchain / Cryptocurrency -> Crypto
* E-commerce -> Ecommerce & Retail
* Video games -> Gaming

Why this change was made? I guess it is related to the disappearing strings in #244.

Also, it looks like "Tech & IT" was added. But this doesn't make sense as an industry in this context, so I'd like to remove it.

**Comment by SachaG** [comment]
I think the changes might be due to switching over to loading most strings from the "generic" Devographics locales instead of the specific TokyoDev repo. 

"Blockchain / Cryptocurrency" does sound more descriptive than just "Crypto" so I might change it back though.

**Comment by SachaG** [comment]
Also I don't remember if it's relevant for that specific question, but I usually try to incorporate any freeform result from the past year into the options for the next (e.g. if 20 people mentioned Agriculture in the "other…" field, then I would make that a default option, and on the contrary if only 3 people pick "E-commerce" then I might remove it from the provided defaults).

**Comment by pwim** [comment]
It seems some of them have been translated in the meantime?

Here's the outstanding ones

* Advertising -> 広告
* Artificial Intelligence (AI) -> 人工知能 (AI)
* Cloud Computing -> クラウドコンピューティング
* Crypto -> 暗号資産
* SaaS (Software as a Service) (leave as is)

And remove "Tech & IT"

**Comment by SachaG** [comment]
ok, done
