### ISSUE TITLE
Japanese translation fixes

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#245]
Here's some more Japanese to fix.

> “Leave an issue” is in the footer of the first page, and should have been something like “Report an issue”.
→ Then the Japanese should be “問題を報告する”

I also found some parts that could be improved.

First page:

> 2024年のTokyoDev調査へようこそ！完了するまでに約10分かかる予定です。
→ ”2024年版TokyoDev Surveyへのご協力ありがとうございます！全質問への回答には10分程度かかります”

> 多様性に関する情報収集と公開がセンシティブな問題になりうることは承知しています。その上で、このアンケートの包括性や代表性を知り、また向上させるためにデータを収集することが重要と考えています。
→多様性に関する情報収集と公開がセンシティブな問題になりうることは認識しています。その上で、本アンケートの包括性を維持し、ジェンダーに関する問題の改善のためにはデータが重要と考え、設問に加えています。

> 雇用主（in ソフトウェア開発者として何社で働きましたか？section)
→社

On “現在の仕事” page:

> 是認が女性かノンバイナリー (in エンジニアの同僚の性別は？section)
→ 是認→自認

On “給与” page:

> 現在の勤務先における年収の合計は？
→ Pull down options appear in English.

On “その他の質問” page:
> 日本での生活の満足度は？
→ 生活の質の満足度Quality of Life Satisfaction

**Comment by SachaG** [comment]
> 是認が女性かノンバイナリー (in エンジニアの同僚の性別は？section)

This should be `全員が自認女性かノンバイナリー` right?

**Comment by pwim** [comment]
Yeah, that's my understanding. Thanks!
