### ISSUE TITLE
Clean up Source

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#256]
10 respondents apparently came via State of CSS. Did you advertise it there, or is this a bug that's misclassifying results?

---

Additional sources that need cleanup:

- LinkedIn Learning -> LinkedIn
- reddit_ad -> Reddit
- TokyoDev [link]

**Comment by SachaG** [comment]
I'll double-check, I did add TokyoDev links to some places (I need to add them everywhere actually) but those would link to the homepage, not the survey. So probably a misclassifying bug?

**Comment by SachaG** [comment]
This was happening because I was doing pattern-matching based on all surveys (including the CSS one) instead of just TokyoDev. I recalculated all the sources, it should be fine now.
