### ISSUE TITLE
Group hours per week into ranges

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#261]

**Comment by SachaG** [comment]
<img width="833" alt="Screenshot 2024-10-03 at 10 57 10" src="https://github.com/user-attachments/assets/f90ded3e-d6e1-4912-8640-d580215dff7a">

Would that work or do we want to be more granular towards the middle?

**Comment by pwim** [comment]
I think there's a significant difference between 40 and 49 hours, so we probably want more granularity there.

Also, I think that most of the under 10 hours is garbage data, as people misread the question as number of hours per day. Not sure what we want to do about this.

**Comment by SachaG** [comment]
For the under-10 hours, we can merge that into under-20 so it's less apparent? But it might not be garbage data, the 4-hour work-week is a thing…

**Comment by pwim** [comment]
70% of people who said "less than 10 hours" were working for a Japanese employer. So I think it's more likely that they misunderstood.

I suppose we can call out that issue in the summary.
