### ISSUE TITLE
Clean up salary ranges

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#263]
- Remove Over ¥20.0m (as we're now having higher ranges)
- Fix labels (¥30.0m-39.9m instead of ¥30,000,000 to ¥39,999,999 per year)
- Remove options with no answers

**Comment by SachaG** [comment]
For the higher ranges, would the following grouping work?

- ...
- range_15000000_to_19999999 (same as before)
- range_20000000_to_29999999 (new)
- range_30000000_to_49999999 (new)
- range_over_50000000 (new)

**Comment by SachaG** [comment]
<img width="878" alt="Screenshot 2024-10-03 at 10 34 01" src="https://github.com/user-attachments/assets/bce367ba-bd4d-4cea-9b71-571cd92d99c8">

**Comment by pwim** [comment]
Yeah that should work.
