### ISSUE TITLE
Professional experience as a custom filter

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#268]
When I select professional experience as a series, it looks like it is being treated as an integer and doesn't work.

**Comment by SachaG** [comment]
Hmm… we collect numerical data for that question so we could in theory get series based on individual numbers (e.g. "years of experience = 5") but I think it probably makes more sense to use the same groups we use to visualize the data (e.g. "years of experience between 5 and 10")?

I think that's already how it's supposed to work, I'll look into it. 

The "facet" view works on the other hand:

<img width="875" alt="Screenshot 2024-10-03 at 14 59 50" src="https://github.com/user-
attachments/assets/daaeb805-6633-4040-9b0f-d77a92f8c4eb">

**Comment by pwim** [comment]
Yes, it's fine if we use the same groups.
