### ISSUE TITLE
Theme differently than 2023 results

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#272]
A different colour scheme would help avoid confusing 2023 and 2024 results.

**Comment by SachaG** [comment]
<img width="1259" alt="Screenshot 2024-10-07 at 9 43 14" src="https://github.com/user-attachments/assets/75548bc8-7f3d-455c-b4a3-d87909a50d4f">

Would green work? Or maybe orange?

**Comment by pwim** [comment]
How about changing the background colour as well? That's what's most obvious when comparing versions.
