### ISSUE TITLE
Rows are numbered but ordered alphabetically

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#273]
A minor thing, but I just noticed that there's numbers next to rows that are ordered alphabetically:

<img width="1585" alt="Screenshot 2024-10-07 at 10 55 17" src="https://github.com/user-attachments/assets/c9779c79-d236-4872-9488-4d23d375c3d8">

That remote work is the most popular response but is numbered 8 is confusing.

**Comment by SachaG** [comment]
RIght, that's mainly there for questions that are ranked numerically so you can see at a glance an item's ranking. I guess we should just hide them when the options are not ranked?
