### ISSUE TITLE
Paid leave percentage facet not working?

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#276]
Looks off to me:

<img width="1121" alt="Screenshot 2024-10-09 at 10 15 56" src="https://github.com/user-attachments/assets/147202ef-62e1-496c-a9e3-199e4e1f9449">

**Comment by SachaG** [comment]
Right, this is because when we use ranges such as `range_0_19`, I manually define the lower bound, upper bound, and average of the range (although I should probably calculate it all instead): 

```
        - id: range_0_19
          lowerBound: 0
          average: 10
          upperBound: 20
  ```
  
These values were off.
