### ISSUE TITLE
Japanese prefecture tab

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#277]
Add tab for other.life_in_japan__social_life facet.

**Comment by SachaG** [comment]
<img width="1105" alt="Screenshot 2024-10-22 at 10 26 16" src="https://github.com/user-attachments/assets/41b32c2b-58f8-4c98-8af4-1784cfc85c1d">

**Comment by SachaG** [comment]
The raw numbers (3, 2, etc.) are a bit abstract but I'm not sure what else to display. Maybe we just explain them in the takeaway text?
