### ISSUE TITLE
In facets, categorize gender as male / not-male

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#279]
We currently aren't displaying anything useful, as our privacy protections combine with insufficient responses of non-binary people mean the most of the time it shows up as "insufficient data".

**Comment by SachaG** [comment]
How about "men" and "women/non-binary"? "men" vs "non-men" feels very male-centric…

This would also affect the main Gender chart, is that ok?

**Comment by pwim** [comment]
Seeing the implementation of this, I'm questioning if we should have done it. 

For instance, this makes it look like the pay gap between women and men is lower, as non-binary people tend to be in the middle (something that's also lost).

Sorry, but let's revert this change.

**Comment by SachaG** [comment]
OK, I'll revert it and regenerate the data. Let me know if anything looks weird.
