### ISSUE TITLE
Hours per Day chart

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#28]
<img width="952" alt="Screenshot 2023-10-17 at 14 25 21" src="https://github.com/SachaG/tokyodev/assets/358832/3d14a8d8-dc31-4321-83ce-1a831013ffd8">

- How do we visualize this? Ranked by counts, or sorted by number of hours?
- What do we do with invalid values?

**Comment by pwim** [comment]
I'd like to

* Treat any answer > 24 as no answer
* 4 or less, 5, 6, 7, 8, 9, 10 or more
* Round 7.5 to 7 (As part of the description, we can say we rounded down, and that 2.4% of question respondents said they work 7.5 hours)

**Comment by SachaG** [comment]
> Treat any answer > 24 as no answer

Would it be ok to just delete them from the database then? that will probably be easier than finding a place to write it a special edge case for that question?

**Comment by pwim** [comment]
Based on my understanding of your implementation, removing answers of 24+ when you’re processing the raw results to the processed ones sounds like the right approach.

**Comment by SachaG** [comment]
<img width="1047" alt="Screenshot 2023-11-12 at 19 14 39" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/b7030e99-2a11-4209-97ea-9c2421c83c1f">
