### ISSUE TITLE
Job Search Status

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#286]
Add a remote work policy tab

Contents would ideally be

![Actively looking vs  Remote Work Policy](https://github.com/user-attachments/assets/521d6178-3747-49b3-9fb9-b06595f9ef08)

But I don't think that's possible. The alternative would be

<img width="1123" alt="Screenshot 2024-10-10 at 11 04 27" src="https://github.com/user-attachments/assets/ab7b7bb3-4f31-44ae-a1ad-8f0303ae6b59">

**Comment by SachaG** [comment]
Note: the `most_important_benefit_by_remote_work_policy` chart does not have "no remote work". Should we add it there too to make them the same?
