### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#287]
Add "Compensation by experience"
<img width="1584" alt="Screenshot 2024-10-10 at 11 22 39" src="https://github.com/user-attachments/assets/587ff761-6417-4492-8a81-7cc20332f758">

Ideally we have some sort of custom chart to let us compare Junior vs Mid vs Senior experience.

**Comment by SachaG** [comment]
What would that custom chart look like?

**Comment by SachaG** [comment]
Also was leaving out the "under 1 year" bucket on purpose?

**Comment by SachaG** [comment]
Actually the code that runs at build time doesn't support mixing filters and facets like this just yet, so I'll have to come back to that.

**Comment by SachaG** [comment]
See https://github.com/Devographics/Monorepo/issues/437

**Comment by SachaG** [comment]
<img width="1090" alt="Screenshot 2024-10-24 at 14 11 13" src="https://github.com/user-attachments/assets/e26ee65e-23e5-4dab-ac1b-9f414627ec77">

I limited each chart to the first 10 items, sorted from highest median salary to lowest.
