### ISSUE TITLE
Colleague Nationality (Engineers)

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#289]
- Remove by years in Japan
- Add Reason for Relocation is I was born in Japan / Reason for Relocation is not one of I was born in Japan

**Comment by SachaG** [comment]
<img width="1075" alt="Screenshot 2024-10-22 at 15 22 11" src="https://github.com/user-attachments/assets/e0d1a1b2-cd0c-4b7a-ad9b-36604b6fba0c">

Are there enough datapoints to make this worth including?
