### ISSUE TITLE
Colleague Nationality (Non-Engineers)

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#290]
- Remove "By Years In Japan"
- Add Facet "Colleague Nationality (Engineers)"

**Comment by SachaG** [comment]
<img width="1090" alt="Screenshot 2024-10-22 at 15 24 52" src="https://github.com/user-attachments/assets/31dbbd3f-ed16-4f66-8497-2f60741653b8">

Maybe it's just me but it seems hard to understand?

**Comment by SachaG** [comment]
<img width="1062" alt="Screenshot 2024-10-26 at 7 10 07" src="https://github.com/user-attachments/assets/6cce0188-83a6-4e7f-9a96-74004b85cc94">

This seems weird?

**Comment by SachaG** [comment]
I assume it's supposed to be `…where all their colleagues were non-Japanese.`
