### ISSUE TITLE
Bug when creating a custom chart

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#292]
<img width="1128" alt="Screenshot 2024-10-16 at 16 19 07" src="https://github.com/user-attachments/assets/bac2ae08-9de1-4b71-8df8-3130d1c2ecdf">

**Comment by pwim** [comment]
This bug only occurs with saved charts. I've noticed that weirdness occurs between deploys with them. Maybe you need a mechanism to reset saved charts?

**Comment by SachaG** [comment]
Resetting them seems really hard, I'm not sure based on what criteria I would know when to reset them. I think our best bet is to just try not to mess them up too much once the survey results go live…
