### ISSUE TITLE
Co-workers Gender

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#295]
- Sorting for salary breakdown
- Add Gender tab: Gender is one of Man / Gender is not one of Man

**Comment by SachaG** [comment]
<img width="1069" alt="Screenshot 2024-10-22 at 10 35 19" src="https://github.com/user-attachments/assets/4fdb5467-717c-4a58-859a-570f91ab1ee5">

The gender of respondents does not seem to correlate with the gender of their co-workers. I don't know if we need that chart?

**Comment by pwim** [comment]
That it isn't correlated is the point I wanted to make.
