### ISSUE TITLE
Workplace Perks

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#297]
By Job Search Status: Job Search Status is Yes, I'm actively looking for a new job. / Job Search Status is No

**Comment by SachaG** [comment]
<img width="1085" alt="Screenshot 2024-10-22 at 15 18 44" src="https://github.com/user-attachments/assets/74cd7699-46fc-436d-807a-e7a388bf5401">

This doesn't seem that significant? Is it worth including?
