### ISSUE TITLE
Job search status and gender

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#3]
<img width="906" alt="Screenshot 2023-10-24 at 16 53 45" src="https://github.com/SachaG/tokyodev/assets/30756/7fc048e6-f084-465e-b6c7-6551ccba23db">

I guess "Yes" is insufficient data. However, it is also implicit that the remaining 16% would be "Yes". 

Not sure how to best handle this situation, and if it implies some other problem with our anonymization scheme.

**Comment by SachaG** [comment]
I'm not quite sure what to do about this, to be honest I feel like it's probably an acceptable level of risk? I'm just worried if we take measures to remove that data we'll end up with charts that don't have much meaning since almost all of them will be "insufficient data" bars.

**Comment by SachaG** [comment]
That being said, I think this would solve the issue?

- If any data row has only a single "insufficient data" segment, then also mark the next lowest segment as "insufficient data"

**Comment by pwim** [comment]
It's no longer clear what the initial scenario was as the image is broken...

However, I think your point here is correct:

> If any data row has only a single "insufficient data" segment, then also mark the next lowest segment as "insufficient data"

I think in most cases, more than one segment will have insufficient data, and so we won't be losing anything there. Whereas it should protect against someone crafting a specific filter to expose data.

**Comment by SachaG** [comment]
OK, I've added that step.
