### ISSUE TITLE
Employer Type

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#300]
Compensation By Experience
  - Total Compensation facet
  - Series
    - Under 1
    - 1 - 3
    -  4 - 6, 7 -9
    - 10 - 12, 13 - 15, 16 - 20, 20+

**Comment by SachaG** [comment]
Using "open" ranges (<1, >20, etc.) within filters is not supported. It's something I need to work on but it might take me an extra day of work to rethink that whole part of the logic.

**Comment by SachaG** [comment]
See https://github.com/Devographics/Monorepo/issues/436

**Comment by SachaG** [comment]
<img width="1149" alt="Screenshot 2024-10-25 at 15 49 39" src="https://github.com/user-attachments/assets/e78b27c3-c3aa-46e8-a364-d4ea478330dc">

This one took some work but I think I got there in the end.
