### ISSUE TITLE
Employer Size

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#303]
* ¥20m+ tab: Total Compensation is one of ¥30.0-49.9m, Over ¥50.0m, ¥20.0-29.9m

**Comment by SachaG** [comment]
<img width="1094" alt="Screenshot 2024-10-22 at 10 30 28" src="https://github.com/user-attachments/assets/11c97574-712e-48b0-8897-d8a04dfd4aa9">

Seems we don't have enough data in those high salary ranges? Or did I make a mistake somewhere?

**Comment by pwim** [comment]
This is the chart I want.
