### ISSUE TITLE
Paid Leave Percentage

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#305]
* Sort in logical order on salary breakdown
* Add "By Colleague Nationality" Colleague Nationality (Engineers) is one of All Japanese / Colleague Nationality (Engineers) is one of All non-Japanese

**Comment by SachaG** [comment]
<img width="1074" alt="Screenshot 2024-10-22 at 10 31 25" src="https://github.com/user-attachments/assets/836adc17-55df-422c-b17b-ac2258890e97">

Maybe we broaden it to "all of japanese + mostly japanese"?

**Comment by pwim** [comment]
No, I'm focused on the difference between who takes 80% plus of their holidays.

It's also a different chart than the one you have:

<img width="1145" alt="Screenshot 2024-10-23 at 11 23 47" src="https://github.com/user-attachments/assets/2ff2b863-3f9d-4d8f-9e66-cd34e62725ef">

**Comment by SachaG** [comment]
Oh, so the idea is that if your colleagues are all japanese you're less likely to take holidays, presumably because they don't either?

Also yes I get your version too now.

**Comment by SachaG** [comment]
<img width="1093" alt="Screenshot 2024-10-23 at 11 29 09" src="https://github.com/user-attachments/assets/eba0db2b-17e9-4766-a23b-c921d91fa9b7">
