### ISSUE TITLE
Reduce prominence of question?

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#318]
Having the question immediately after the title puts a lot of emphasis on it (more so than the takeaway):

<img width="1344" alt="Screenshot 2024-10-28 at 15 31 18" src="https://github.com/user-attachments/assets/856a0233-fde0-4cfb-bdd1-16dccfbc6df8">

Is it that important? I could see putting it after the chart, or even in the footer (with mean, median, etc).

**Comment by SachaG** [comment]
<img width="1152" alt="Screenshot 2024-10-29 at 11 40 49" src="https://github.com/user-attachments/assets/ea19ac78-40ea-4d55-9224-94d2f76fafa5">

I don't have a strong opinion, we can try it that way.
