### ISSUE TITLE
Professional Experience -> Gender

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#319]
Gender is not one of Man -> Gender is Woman

**Comment by SachaG** [comment]
This means excluding non-binary respondents from the data? I feel like that might be problematic?

**Comment by pwim** [comment]
Just for this one chart. I don't feel that comparing women vs men is a problem, as non-binary don't fit into either category (so there's just as much of an issue with lumping them in with women). Ideally we'd be able to compare all three, but I don't think there's enough data for non-binary respondents anyway.
