### ISSUE TITLE
New Question: Top Expenses

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#32]
What are your top 3 expenses?
daily life
savings
sending money abroad
leisure

**Comment by pwim** [comment]
Looking at my own expenses last year, it'd be:

1. Rent
2. Children (daycare, baby sitters, clothing, etc)
3. Groceries
4. Utilities (Electricity, Gas)
5. Holiday and Leisure
6. Life insurance
7. Games
8. Car (Fuel, Auto Insurance, Tollway fees)
9. Eating Out
10. Gym & Fitness

But I also think unless you're tracking them, it might be kind of hard to tell, and I suspect most people are going to have the same top 4 as me (or 3 if no Children).
