### ISSUE TITLE
Total Employers vs Professional Experience tab

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#321]
{
  "options": {
    "showDefaultSeries": false,
    "enableYearSelect": false,
    "mode": "default",
    "queryOnLoad": false,
    "cutoff": 1,
    "cutoffType": "percent",
    "limit": 20,
    "mergeOtherBuckets": false,
    "preventQuery": false
  },
  "filters": [],
  "facet": {
    "sectionId": "user_info",
    "id": "years_of_experience"
  }
}

**Comment by SachaG** [comment]
<img width="1095" alt="Screenshot 2024-10-30 at 11 16 22" src="https://github.com/user-attachments/assets/ac65d3cf-ed35-407d-8d64-4e5d382d31ad">
