### ISSUE TITLE
Display country names instead of code

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#328]
`NPL` is showing up as the 13th most popular country. It seems like you're only giving country names for a subset of countries. There should be an easy way of going from country code to country name (I did this in Ruby using a library for instance).

**Comment by SachaG** [comment]
Right, this is because I thought if I included all possible country names it would be a lot of unnecessary stuff to translate since most of them will never appear in the data. So it's a manually curated subset currently. 

I'll add Nepal.

**Comment by pwim** [comment]
If you use a library for country names, they should already have translations baked in. At least the Ruby one I'm using does.

The problem with the current approach is that it means some people need to select their country code when taking the survey. It makes them feel like an after though at best, not fill it in at worst.
