### ISSUE TITLE
New Question: Extra Revenue

### ISSUE THREAD

**Issue by SachaG** [tokyodev-inc/tokyodev-devographics#33]
How much of your total revenue do you get from extra work done outside of your primary employer?
0-30%
30-60%

**Comment by pwim** [comment]
As we're asking about total compensation, I'm not sure that this question makes sense.

If I were to ask it, it would be something like, "Do you earn income from any of the following?", with options like:

- Freelancing
- Selling products
- Blogging
- Vlogging
- Investments
