### ISSUE TITLE
Productivity Tools

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#332]
- Job Search Status facet
  - Sort by "Actively looking, descending"
- Industry facet

**Comment by SachaG** [comment]
<img width="1082" alt="Screenshot 2024-11-05 at 15 28 17" src="https://github.com/user-attachments/assets/5bfac473-2145-4e70-b44e-613e2420d168">

<img width="1097" alt="Screenshot 2024-11-05 at 15 28 24" src="https://github.com/user-attachments/assets/9efd55e1-359a-4f6e-989c-708c12404864">
