### ISSUE TITLE
Number of Applications

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#333]
Facet tabs:
- Professional experience
- Years in Japan

**Comment by SachaG** [comment]
<img width="1090" alt="Screenshot 2024-11-01 at 15 02 01" src="https://github.com/user-attachments/assets/84762f6d-128b-404d-aac8-8461eb305b06">
<img width="1098" alt="Screenshot 2024-11-01 at 15 02 09" src="https://github.com/user-attachments/assets/3fc20a12-ec2e-4d3e-9bd4-b1988c39768c">
