### ISSUE TITLE
Translations for life_in_japan__professional_life etc

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#350]
We're showing the raw attributes now.

**Comment by SachaG** [comment]
Where is that?

**Comment by pwim** [comment]
In the filter dropdown.

**Comment by SachaG** [comment]
<img width="507" alt="Screenshot 2024-11-14 at 14 58 45" src="https://github.com/user-attachments/assets/b74597da-15c4-43c6-a90f-a0fcc027d22c">
