### ISSUE TITLE
Labels for combined chart wrong

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#4]
Looks like an off by one error:
<img width="912" alt="Screenshot 2023-10-24 at 15 50 00" src="https://github.com/SachaG/tokyodev/assets/30756/0c9e52a9-d7b0-4aa8-b1fe-5ab20e665196">

**Comment by SachaG** [comment]
Because of the issue transfer we lost the screenshot so it's hard to know what this was referring to, but I'll assume it's fixed unless you encounter the same issue again.
