### ISSUE TITLE
Translate to Japanese

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#84]
I’d like to translate the results to Japanese. Can you point me to which files should be translated?

**Comment by SachaG** [comment]
The files are all here:

https://github.com/tokyodev-inc/tokyodev-devographics/tree/main/locales/locale-ja-JP

### TokyoDev Translations

https://github.com/tokyodev-inc/tokyodev-devographics/blob/main/locales/locale-ja-JP/tokyodev.yml contains all strings that are unique to TokyoDev, and have not been translated yet. 

### Other Translations

All other files contain strings that are issues from the other Devographics surveys, mainly for user interface. Some of them have been translated to Japanese already, which should save some time. 

Caveats:

- The translations were done by volunteers so the quality might not always be perfect
- There are a few strings that I've added recently that will not have been translated

**Comment by pwim** [comment]
I noticed there's a bunch of commented out stuff. Can that be removed?

Also, it looks like the keys in this are both for taking the survey itself, and the results. Is there any easy way so we could just translate the results strings?

**Comment by SachaG** [comment]
Yes we can ignore the commented out stuff. 

In theory anything in `results.yml` is only for results. It's true it's mixed in `tokyodev.yml` but since most things show up in both places it's a bit hard to differentiate them…

**Comment by pwim** [comment]
With the current translation strategy, I think it is going to be quite hard for Keiko to help out with this. I think we'll stick with English for now.
